### ISSUE TITLE
WordCount.java

### ISSUE THREAD

**Issue by jatindergoel444** [dapurv5/MapReduce-BSP-Adapter#1]
actual and formal argument lists differ in length

**Comment by dapurv5** [comment]
Can you point at the actual method?
This was written against Hama 0.7.0-SNAPSHOT so things might have changed. But happy to resolve the issue if you can point what has changed.

**Comment by jatindergoel444** [comment]
Actually, I am using Hama 0.7.1 so I changed the version of dependencies in POM file and tried to create a jar file with the help of maven 3.3.9. but it shows error in Wordcount.java file.

Thanks for your help in advance

**Comment by dapurv5** [comment]
Can you please paste your error here.

**Comment by jatindergoel444** [comment]
Here is the error posted:

pi@raspberrypi:~/Desktop/MapReduce-BSP-Adapter-master/MapReduce-BSP-Adapter-master $ mvn clean package install[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building MapReduce-BSP-Adapter 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ MapReduce-BSP-Adapter ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ MapReduce-BSP-Adapter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ MapReduce-BSP-Adapter ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 10 source files to /home/pi/Desktop/MapReduce-BSP-Adapter-master/MapReduce-BSP-Adapter-master/target/classes
[INFO] /home/pi/Desktop/MapReduce-BSP-Adapter-master/MapReduce-BSP-Adapter-master/src/main/java/org/apache/hama/mapreduce/MapRedBSP.java: Some input files use or override a deprecated API.
[INFO] /home/pi/Desktop/MapReduce-BSP-Adapter-master/MapReduce-BSP-Adapter-master/src/main/java/org/apache/hama/mapreduce/MapRedBSP.java: Recompile with -Xlint:deprecation for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/pi/Desktop/MapReduce-BSP-Adapter-master/MapReduce-BSP-Adapter-master/src/main/java/org/apache/hama/mapreduce/examples/WordCount.java:[31,13] constructor LexicalizedParser in class edu.stanford.nlp.parser.lexparser.LexicalizedParser cannot be applied to given types;
  required: edu.stanford.nlp.parser.lexparser.Lexicon,edu.stanford.nlp.parser.lexparser.BinaryGrammar,edu.stanford.nlp.parser.lexparser.UnaryGrammar,edu.stanford.nlp.parser.lexparser.DependencyGrammar,edu.stanford.nlp.util.Index<java.lang.String>,edu.stanford.nlp.util.Index<java.lang.String>,edu.stanford.nlp.util.Index<java.lang.String>,edu.stanford.nlp.parser.lexparser.Options
  found: java.lang.String
  reason: actual and formal argument lists differ in length
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.886 s
[INFO] Finished at: 2016-07-18T10:53:19+08:00
[INFO] Final Memory: 20M/49M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project MapReduce-BSP-Adapter: Compilation failure
[ERROR] /home/pi/Desktop/MapReduce-BSP-Adapter-master/MapReduce-BSP-Adapter-master/src/main/java/org/apache/hama/mapreduce/examples/WordCount.java:[31,13] constructor LexicalizedParser in class edu.stanford.nlp.parser.lexparser.LexicalizedParser cannot be applied to given types;
[ERROR] required: edu.stanford.nlp.parser.lexparser.Lexicon,edu.stanford.nlp.parser.lexparser.BinaryGrammar,edu.stanford.nlp.parser.lexparser.UnaryGrammar,edu.stanford.nlp.parser.lexparser.DependencyGrammar,edu.stanford.nlp.util.Index<java.lang.String>,edu.stanford.nlp.util.Index<java.lang.String>,edu.stanford.nlp.util.Index<java.lang.String>,edu.stanford.nlp.parser.lexparser.Options
[ERROR] found: java.lang.String
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

and i have also attached the changed POM.xml file: (in txt format)
[pom .txt](https://github.com/dapurv5/MapReduce-BSP-Adapter/files/368289/pom.txt)

**Comment by dapurv5** [comment]
Please pull the latest changes, all bugs should be fixed now.
